server {
    listen 80;
    server_name _;

    root /var/www/app/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/app/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /var/www/app/public;
        fastcgi_pass codeigniter-php-fpm:9000;
        fastcgi_read_timeout 60s;
    }
}
